name: workflowtwo

on:
 
 repository_dispatch:
    types: [trigger-workflow-2]
 
jobs:
  one:
    runs-on: ubuntu-16.04
    steps:
      - name: run something
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "Hello World"
